# -*- coding: utf-8 -*-
"""iris_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FtFzeoAZdF5yOggaca2GRsZuEj1Z4fd
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('iris.csv')

print("First few rows of the dataset:")
print(data.head())

print("\nMissing values in the dataset:")
print(data.isnull().sum())

print("\nSummary statistics:")
print(data.describe())

print("\nData distribution by species:")
print(data['species'].value_counts())

sns.pairplot(data, hue='species')
plt.title('Pairplot of Iris Dataset')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='sepal_length', data=data)
plt.title('Boxplot of Sepal Length by Species')
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(data.drop('species', axis=1).corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

X = data.drop('species', axis=1)
y = data['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("\nModel Evaluation:")
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))